from fastapi import APIRouter, HTTPException

from backend.schemas.solve import (
    SolveRequest,
    SolveResponse,
    RouteResponse
)

from backend.solver.solver_registry import get_solver
from backend.models.order import Order
from backend.utils.scene_loader import load_scene
from backend.utils.order_generator import generate_orders
from backend.utils.problem_builder import build_problem


router = APIRouter()


@router.post("/solve", response_model=SolveResponse)
def solve_vrp(request: SolveRequest):
    """
    Full simulation pipeline:

        load_scene()        static world (map + nodes)
        orders              random: generated by backend
                            custom: supplied by the frontend
        build_problem()     orders + vehicle params -> VRPProblem
        get_solver().solve()
        translate routes from solver indices back to scene node ids
    """

    config = request.config

    # ---- 1. Static scene ----
    try:
        scene_map = load_scene(request.scene)
    except (ValueError, FileNotFoundError) as exc:
        raise HTTPException(
            status_code=400,
            detail=str(exc)
        )

    # ---- 2. Order layer: random generation or client-supplied orders ----
    try:
        if config.mode == "random":
            orders = generate_orders(
                scene_map,
                mode="random",
                order_count=config.order_count,
                seed=config.seed
            )

        elif config.mode == "custom":
            if not config.orders:
                raise ValueError(
                    "'custom' mode requires a non-empty 'orders' list"
                )

            orders = [
                Order(
                    order_id=index,
                    customer_id=item.customer_id,
                    demand=item.demand
                )
                for index, item in enumerate(config.orders)
            ]

        else:
            raise ValueError(
                f"Unsupported order mode: '{config.mode}'. "
                f"Supported modes: ['random', 'custom']"
            )

        # ---- 3. Orders -> VRPProblem (validates customer ids) ----
        problem, solver_to_scene = build_problem(
            scene_map,
            orders,
            vehicle_count=config.vehicle_count,
            vehicle_capacity=config.capacity
        )
    except ValueError as exc:
        raise HTTPException(
            status_code=400,
            detail=str(exc)
        )

    # ---- 4. Solve ----
    try:
        solver = get_solver(request.algorithm)
        result = solver.solve(problem)
    except ValueError as exc:
        raise HTTPException(
            status_code=400,
            detail=str(exc)
        )

    if result is None:
        raise HTTPException(
            status_code=400,
            detail="Solver failed to find a feasible solution."
        )

    # ---- 5. Translate solver indices -> stable scene node ids ----
    routes = []

    for index, route in enumerate(result.routes):

        routes.append(
            RouteResponse(
                vehicle_id=index,
                route=[
                    solver_to_scene[node_id]
                    for node_id in route
                ]
            )
        )

    return SolveResponse(
        scene=scene_map.scene_id,
        algorithm=result.algorithm,
        routes=routes,
        total_distance=result.total_distance
    )
